version: '3.7'
services:
  bitcoind:
    image: lncm/bitcoind:0.18.0-linux-arm
    volumes:
      - /media/archive/archive/bitcoin/:/root/.bitcoin/
    network_mode: host

  lnd:
    image: lncm/lnd:0.6-linux-arm
    volumes:
      - /media/volatile/volatile/lnd/logs:/root/.lnd/logs
      - /media/important/important/lnd/data:/root/.lnd/data
      - /media/important/important/lnd/lnd.conf:/root/.lnd/lnd.conf
      - /media/important/important/lnd:/root/.lnd
      - /var/lib/tor:/var/lib/tor
    depends_on:
      - bitcoind
    restart: on-failure
    network_mode: host

  invoicer:
    image: lncm/invoicer:0.1.1
    volumes:
      - /media/important/important/lnd:/lnd
      - /home/lncm/public_html:/static
    depends_on:
      - lnd
    restart: on-failure
    environment:
      - LNDHOST=localhost
      - LNDPORT=10009
      - PORT=8088
      - GRPC_GO_RETRY=on
      - BTCHOST=localhost
      - BTCRPCUSER=RANDOMUSER
      - BTCRPCPASS=RANDOMPASS
      - INVOICER_HOSTPORT=invoicer:defaultpassw0rd@localhost:8088
      - STATICDIR=/static/
    network_mode: host
