plugins:
  pep8:
    enabled: true
  bandit:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  radon:
    enabled: true 
  shellcheck:
    enabled: true
  sonar-python:
    enabled: false
 
